[package]
edition = "2021"
name = "wwida"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
bson = "2.3.0"
chrono = {version = "0.4.19", features = ["serde"]}
clap = {version = "3.2.16", features = ["derive"]}
home = "0.5.3"
itertools = "0.10.3"
serde = {version = "1.0", features = ["derive"]}
